apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: elastic
  name: elastic
spec:
  containers:
  - image: elastic
    name: elastic
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}