apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-enp10s0-policy 
spec:
  desiredState:
    interfaces:
      - name: br1 
        description: Linux bridge with enp10s0 as a port 
        type: linux-bridge 
        state: up 
        ipv4:
          enabled: false
          dhcp: false 
        bridge:
          options:
            stp:
              enabled: false 
          port:
#            - name: enp10s0
            - name: ens224