apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: postgres
  name: postgres
spec:
  containers:
  - image: postgres
    name: postgres
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}