apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: prodpool #the name of the pool you want to use
  namespace: metallb-system
spec:
  addresses:
 # - 10.0.1.70 - 10.0.1.84 # be sure to update this with the address pool for your lab
 # - 10.0.1.161 - 10.0.1.199
  - 10.253.115.132 - 10.253.115.135
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: prod # the name of the advertisement
  namespace: metallb-system
