apiVersion: stork.libopenstorage.org/v1alpha1
kind: Migration
metadata:
  name: migrate01
  namespace: portworx
spec:
  clusterPair: cluster2
  includeResources: true
  startApplications: true
  namespaces:
    - costco-migrate
  purgeDeletedResources: false
  selectors: 
    pxmigrate: "true"
