apiVersion: stork.libopenstorage.org/v1alpha1
kind: Migration
metadata:
  name: migrate12 #update this name!
  namespace: portworx
spec:
  clusterPair: cluster2
  includeResources: true
  startApplications: true
  namespaces:
    - costco-migration # update this namespace!
  #adminClusterPair: cluster02
  purgeDeletedResources: false
